"""empty message

Revision ID: 06737aa91e07
Revises: 8946e6af724f
Create Date: 2018-03-30 20:59:01.286169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06737aa91e07'
down_revision = '8946e6af724f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rehearsalInvite', sa.Integer(), nullable=True),
    sa.Column('welcomeReceptionInvite', sa.Integer(), nullable=True),
    sa.Column('rehearsalFoodChoice', sa.String(), nullable=True),
    sa.Column('receptionFoodChoice', sa.String(), nullable=True),
    sa.Column('rehearsalRSVPStatus', sa.String(), nullable=True),
    sa.Column('welcomeReceptionRSVPStatus', sa.String(), nullable=True),
    sa.Column('receptionRSVPStatus', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guests2')
    # ### end Alembic commands ###
