"""empty message

Revision ID: 8df78bab7728
Revises: c49597a82af3
Create Date: 2018-03-31 00:06:40.903393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df78bab7728'
down_revision = 'c49597a82af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guests2')
    op.drop_table('guests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('party', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rehearsalInvite', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('welcomeReceptionInvite', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rehearsalFoodChoice', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('receptionFoodChoice', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rehearsalRSVPStatus', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('welcomeReceptionRSVPStatus', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receptionRSVPStatus', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='guests_pkey')
    )
    op.create_table('guests2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('party', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rehearsalInvite', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('welcomeReceptionInvite', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rehearsalFoodChoice', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('receptionFoodChoice', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rehearsalRSVPStatus', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('welcomeReceptionRSVPStatus', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('receptionRSVPStatus', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='guests2_pkey')
    )
    # ### end Alembic commands ###
