"""empty message

Revision ID: d0c799f18682
Revises: 8df78bab7728
Create Date: 2018-03-31 22:11:59.146689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c799f18682'
down_revision = '8df78bab7728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('party', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rehearsalInvite', sa.Integer(), nullable=True),
    sa.Column('welcomeReceptionInvite', sa.Integer(), nullable=True),
    sa.Column('brunchInvite', sa.Integer(), nullable=True),
    sa.Column('rehearsalRSVPStatus', sa.String(), nullable=True),
    sa.Column('welcomeReceptionRSVPStatus', sa.String(), nullable=True),
    sa.Column('receptionRSVPStatus', sa.String(), nullable=True),
    sa.Column('brunchRSVPStatus', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rsvpchoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rsvpchoices')
    op.drop_table('guests')
    # ### end Alembic commands ###
